import type { ModuleState, XYAssignment } from '../../ui/types';

type DreamFrame = { modules: ModuleState[]; assignments: XYAssignment[]; x: number; y: number; dragging: boolean; time: number };
type PatchField = { xStrength: number; yStrength: number };
type ArtLayers = { ember?: ModuleState; drift?: ModuleState; halo?: ModuleState; atmos?: ModuleState; grain?: ModuleState; artifact?: ModuleState };
type WorldProfile = { seed: number; horizon: number; heroX: number; heroLift: number; symmetry: number };
type SceneState = { a: WorldProfile; b: WorldProfile; mix: number; crest: number };
type Geometry = { horizon: number; heroX: number; heroY: number; ember: number; drift: number; halo: number; atmos: number; grain: number; artifact: number };

const RASTER_W = 112, RASTER_H = 64, ACTIVE_INTERVAL = 1 / 30, IDLE_INTERVAL = 1 / 24, SCENE_SECONDS = 24;
const clamp01 = (v:number) => Math.max(0, Math.min(1, v));
const lerp = (a:number,b:number,t:number) => a + (b-a)*t;
const fract = (v:number) => v-Math.floor(v);
const smoothstep = (a:number,b:number,v:number) => { const t=clamp01((v-a)/Math.max(1e-6,b-a)); return t*t*(3-2*t); };
const followAmount = (rate:number,dt:number) => 1-Math.exp(-rate*Math.max(0,Math.min(.1,dt)));
const hash = (x:number,y=0) => fract(Math.sin(x*127.1+y*311.7)*43758.5453123);
const valueOf = (m:ModuleState|undefined,id:string,fallback=0) => m?.parameters.find(p=>p.id===id)?.value ?? fallback;
const visualAmount = (m:ModuleState|undefined) => m?.enabled && m.available ? clamp01(.18 + Math.sqrt(clamp01(valueOf(m,'mix',0)))*.82) : 0;

function noise(x:number,y:number){ const ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy,ux=fx*fx*(3-2*fx),uy=fy*fy*(3-2*fy); const a=hash(ix,iy),b=hash(ix+1,iy),c=hash(ix,iy+1),d=hash(ix+1,iy+1); return lerp(lerp(a,b,ux),lerp(c,d,ux),uy); }
function fbm(x:number,y:number){ return noise(x,y)*.64 + noise(x*2.03+7.1,y*2.03-3.7)*.27 + noise(x*4.07-2.8,y*4.07+5.2)*.09; }
function profileFor(epoch:number):WorldProfile{ const h=(c:number)=>hash(epoch*17.17+c*9.31,c*3.7); return { seed:epoch*13.71+2.9,horizon:.53+(h(0)-.5)*.075,heroX:(h(1)-.5)*.12,heroLift:.145+h(2)*.09,symmetry:.48+h(3)*.42 }; }

export class DreamFieldEngine {
  private width=1; private height=1; private raster:HTMLCanvasElement|null=null; private rasterCtx:CanvasRenderingContext2D|null=null; private imageData:ImageData|null=null; private lastRasterTime=-Infinity; private lastTime=0; private x=.5; private y=.5; private gesture=0;

  resize(width:number,height:number){ this.width=Math.max(1,width); this.height=Math.max(1,height); if(typeof document==='undefined')return; if(!this.raster){ this.raster=document.createElement('canvas'); this.raster.width=RASTER_W; this.raster.height=RASTER_H; this.rasterCtx=this.raster.getContext('2d',{alpha:true}); this.imageData=this.rasterCtx?.createImageData(RASTER_W,RASTER_H)??null; } }

  render(ctx:CanvasRenderingContext2D,frame:DreamFrame){
    const dt=this.lastTime>0?frame.time-this.lastTime:1/60; this.lastTime=frame.time;
    this.x=lerp(this.x,clamp01(frame.x),followAmount(frame.dragging?20:5,dt)); this.y=lerp(this.y,clamp01(frame.y),followAmount(frame.dragging?20:5,dt)); this.gesture=lerp(this.gesture,frame.dragging?1:0,followAmount(frame.dragging?14:3.6,dt));
    const layers=this.layers(frame.modules),patch=this.patchField(frame.assignments),scene=this.sceneState(frame.time),interval=frame.dragging?ACTIVE_INTERVAL:IDLE_INTERVAL;
    if(frame.time-this.lastRasterTime>=interval||this.lastRasterTime<0){ this.renderRaster(frame.time,layers,patch,scene); this.lastRasterTime=frame.time; }
    ctx.clearRect(0,0,this.width,this.height); ctx.fillStyle='#020406'; ctx.fillRect(0,0,this.width,this.height);
    if(this.raster){ ctx.save(); ctx.imageSmoothingEnabled=true; ctx.imageSmoothingQuality='high'; ctx.drawImage(this.raster,0,0,this.width,this.height); ctx.restore(); }
    const g=this.geometry(layers,patch,scene); this.drawAtmos(ctx,frame.time,layers.atmos,g); this.drawHalo(ctx,frame.time,layers.halo,g,scene); this.drawEmber(ctx,frame.time,layers.ember,g,scene.crest); this.drawDrift(ctx,frame.time,layers.drift,g); this.drawGrain(ctx,frame.time,layers.grain,g); this.drawArtifact(ctx,frame.time,layers.artifact,g);
  }

  private layers(modules:ModuleState[]):ArtLayers{ const find=(id:string)=>modules.find(m=>m.id===id&&m.enabled&&m.available); return {ember:find('saturation'),drift:find('chorus'),halo:find('delay'),atmos:find('reverb'),grain:find('bitcrusher'),artifact:find('media')}; }
  private patchField(assignments:XYAssignment[]):PatchField{ let xd=0,yd=0,xc=0,yc=0; for(const a of assignments){ if(a.axis==='x'){xd+=a.depth;xc++;}else{yd+=a.depth;yc++;} } return {xStrength:xc?clamp01(xd/xc):0,yStrength:yc?clamp01(yd/yc):0}; }
  private sceneState(time:number):SceneState{ const j=time/SCENE_SECONDS,e=Math.floor(j),local=fract(j),mix=smoothstep(.76,1,local); return {a:profileFor(e),b:profileFor(e+1),mix,crest:Math.pow(Math.sin(mix*Math.PI),1.5)}; }
  private geometry(l:ArtLayers,p:PatchField,s:SceneState):Geometry{ const xs=this.x-.5; const horizon=lerp(s.a.horizon,s.b.horizon,s.mix)+(.5-this.y)*(.055+p.yStrength*.025); const heroX=.5+lerp(s.a.heroX,s.b.heroX,s.mix)+xs*(.12+p.xStrength*.06); const heroY=horizon-lerp(s.a.heroLift,s.b.heroLift,s.mix)-(this.y-.5)*.022-this.gesture*.006; return {horizon,heroX,heroY,ember:visualAmount(l.ember),drift:visualAmount(l.drift),halo:visualAmount(l.halo),atmos:visualAmount(l.atmos),grain:visualAmount(l.grain),artifact:visualAmount(l.artifact)}; }

  private mountainSurface(u:number,horizon:number,m:ModuleState|undefined,seed:number,time:number,symmetry:number){
    const amount=visualAmount(m); if(amount<=0)return horizon-.008; const mode=m?.delayAlgorithm??'clean',feedback=valueOf(m,'feedback',.24),character=valueOf(m,'character',.14),width=valueOf(m,'width',.58); const p=u*2-1,q=Math.abs(p),axis=lerp(p,q,symmetry); const n=fbm(axis*(1.12+character*.6)+seed*.11,seed*.07+time*.0018),broad=Math.pow(Math.abs(Math.sin(axis*(3.1+width*2.4)+seed*.31)),3.2); let spire=Math.pow(Math.abs(Math.sin(axis*(11+character*12)+seed)),13-feedback*6),height=.022+n*(.038+amount*.028)+broad*amount*.055;
    if(mode==='tape'){height+=Math.pow(n,1.6)*amount*.045;spire*=.22;} else if(mode==='bbd'){height+=spire*amount*.055;height=Math.round(height*34)/34;} else if(mode==='pingpong'){height=height*(p<0?.65+feedback*.5:1.1-feedback*.18)+spire*amount*.055;} else if(mode==='diffuse'){height=.020+Math.pow(n,1.25)*(.07+amount*.055);spire*=.12;} else if(mode==='scatter'){spire=Math.pow(Math.abs(Math.sin(axis*(17+character*15)+seed*1.3)),18-feedback*8);height+=spire*amount*(.09+character*.06);} else if(mode==='constellation'){spire=Math.pow(Math.abs(Math.sin(axis*13.7+seed)),10);height+=spire*amount*.075;} else height+=spire*amount*.042;
    return horizon-height*(.72+amount*.48);
  }

  private cloudField(u:number,v:number,horizon:number,m:ModuleState|undefined,seed:number,time:number){
    const amount=visualAmount(m); if(amount<=0||v>=horizon)return {density:0,cool:0,warm:0}; const mode=m?.algorithm??'hall',size=valueOf(m,'size',.52),diff=valueOf(m,'diffusion',.74),motion=valueOf(m,'motion',.18),color=valueOf(m,'color',.42),p=u*2-1,drift=time*(.002+motion*.005),base=fbm(p*(.75+(1-size)*.55)+seed*.09+drift,v*(1.35+diff*.6)-drift*.7),detail=noise(p*2.6+seed*.17-drift*1.4,v*3.1+seed*.04),alt=clamp01((horizon-v)/Math.max(.18,horizon)); let density=smoothstep(.46-diff*.10,.76,base+detail*.12)*amount,cool=.55+color*.45,warm=.30+(1-color)*.35;
    if(mode==='room')density*=smoothstep(.42,.03,horizon-v)*.82; else if(mode==='plate')density=Math.pow(clamp01(Math.sin(v*39+base*4+time*.035)*.5+.5),5)*amount*(.25+diff*.5); else if(mode==='cinema'){density=clamp01(density*1.1+Math.pow(clamp01(Math.cos(p*8.5+seed)*.5+.5),7)*alt*amount*.38);warm+=.22;} else if(mode==='cloud')density=smoothstep(.40,.68,base)*amount*(.72+diff*.38); else if(mode==='freeze'){density=Math.pow(smoothstep(.50,.74,base+detail*.18),1.8)*amount*.72;cool=1;warm=.08;} else if(mode==='celestial'){density*=.62;cool=.72;warm=.72;} else if(mode==='aurora'){density=Math.pow(clamp01(Math.sin(p*6.4+v*14+time*(.08+motion*.12))*.5+.5),10)*amount*(.28+diff*.34);cool=1;warm=.28;} else if(mode==='nebula'){density=smoothstep(.34,.68,base+detail*.20)*amount*.88;cool=.84;warm=.74;} else if(mode==='abyss'){density=smoothstep(.38,.65,base)*amount*.54;cool=.28;warm=.06;}
    return {density:clamp01(density),cool:clamp01(cool),warm:clamp01(warm)};
  }

  private waterWave(u:number,v:number,m:ModuleState|undefined,heroX:number,horizon:number,seed:number,time:number){
    const amount=visualAmount(m); if(amount<=0||v<=horizon)return 0; const mode=m?.driftMode??'chorus',rate=valueOf(m,'rate',.094),depth=valueOf(m,'depth',.275),spread=valueOf(m,'spread',.62),motion=valueOf(m,'motion',.32),x=u-.5,y=v-horizon,speed=.12+rate*.62+motion*.16; let wave=0;
    if(mode==='ensemble')wave=(Math.sin(x*42+time*speed)+Math.sin(x*61-time*speed*.72+seed)+Math.sin(y*70+x*19+time*.11))/3; else if(mode==='dimension')wave=Math.sin((Math.abs(x)*(38+spread*22)+y*16)-time*speed)*(.65+spread*.35); else if(mode==='vibrato')wave=Math.sin(x*(70+depth*45)+time*speed*1.8)*.75; else if(mode==='rotary')wave=Math.sin(Math.hypot(x*1.25,(v-(horizon+.25))*1.9)*(42+spread*8)-time*speed*1.3); else if(mode==='doppler'){const source=heroX+Math.sin(time*speed*.55)*(.08+spread*.08);wave=Math.sin(Math.hypot((u-source)*1.25,y*1.8)*54-time*speed*1.8);} else if(mode==='liquid')wave=(fbm(x*(3.2+depth*2.5)+seed*.1+time*speed*.08,y*6.4-time*speed*.12)-.5)*2; else if(mode==='orbit')wave=Math.sin(Math.hypot((u-heroX)*(1.4+spread*.3),(v-(horizon+.30))*2.2)*46-time*speed)*.7+Math.cos((u-heroX)*34+time*speed*.6)*.3; else wave=Math.sin(x*(46+spread*12)+time*speed)*.62+Math.sin(x*27-time*speed*.68+y*28)*.38;
    return wave*amount*(.45+depth*.55);
  }

  private renderRaster(time:number,l:ArtLayers,p:PatchField,s:SceneState){
    if(!this.rasterCtx||!this.imageData)return; const data=this.imageData.data,g=this.geometry(l,p,s),{horizon,heroX}=g,seed=lerp(s.a.seed,s.b.seed,s.mix),warmBias=clamp01(.52+(this.x-.5)*.24+g.ember*.10); const ma=new Float32Array(RASTER_W),mb=new Float32Array(RASTER_W); for(let px=0;px<RASTER_W;px++){const u=px/(RASTER_W-1);ma[px]=this.mountainSurface(u,horizon,l.halo,s.a.seed,time,s.a.symmetry);mb[px]=this.mountainSurface(u,horizon,l.halo,s.b.seed,time,s.b.symmetry);}
    for(let py=0;py<RASTER_H;py++){const v=py/(RASTER_H-1);for(let px=0;px<RASTER_W;px++){const u=px/(RASTER_W-1),x=u*2-1,field=lerp(fbm(x*.86+s.a.seed*.08+time*.0035,v*1.22-time*.0025),fbm(x*.86+s.b.seed*.08+time*.0035,v*1.22-time*.0025),s.mix),detail=noise(x*2.65+seed*.13-time*.006,v*2.4+seed*.04),surface=lerp(ma[px],mb[px],s.mix),mountain=smoothstep(surface-.008,surface+.006,v)*(1-smoothstep(horizon-.002,horizon+.010,v)); let r=3,gg=6,b=12;
      if(v<horizon){const alt=clamp01((horizon-v)/Math.max(.20,horizon)),hg=Math.exp(-Math.abs(v-horizon)*24);r+=5+alt*9+field*10+hg*(20+warmBias*20);gg+=9+alt*16+detail*12+hg*25;b+=18+alt*30+field*17+detail*12+hg*31;const cloud=this.cloudField(u,v,horizon,l.atmos,seed,time);r+=cloud.density*(10+cloud.warm*38);gg+=cloud.density*(18+cloud.cool*34);b+=cloud.density*(28+cloud.cool*40+cloud.warm*10);if(l.atmos?.algorithm==='abyss'){const a=cloud.density*g.atmos*.44;r*=1-a;gg*=1-a*.82;b*=1-a*.56;}}
      else{const depth=clamp01((v-horizon)/Math.max(.001,1-horizon)),wave=this.waterWave(u,v,l.drift,heroX,horizon,seed,time),water=g.drift,refl=Math.exp(-Math.abs(u-heroX+wave*.012)*(6.8-water*2.8-valueOf(l.drift,'spread',.62)*.8))*(1-depth*.58),wn=noise(x*(3.2+water*1.3)+time*.010,v*8.5-time*.022);r+=3+depth*5+refl*water*(25+warmBias*36);gg+=8+depth*9+refl*water*38;b+=15+depth*17+refl*water*55;const rip=Math.pow(clamp01(wave*.5+.5),8)*water*smoothstep(horizon+.02,.96,v);r+=rip*(8+warmBias*13);gg+=rip*17;b+=rip*27;const gr=(wn-.5)*water*5.5;r+=gr*.55;gg+=gr*.72;b+=gr;if(water<=.01){r*=.72;gg*=.76;b*=.82;}}
      if(mountain>0){const rim=1-smoothstep(.002,.018,Math.abs(v-surface));r=lerp(r,3+rim*(10+g.halo*17),mountain*.95);gg=lerp(gg,7+rim*(15+g.halo*20),mountain*.97);b=lerp(b,10+rim*(20+g.halo*24),mountain*.96);}
      if(g.drift>.01&&v>horizon){const rv=horizon-(v-horizon)+this.waterWave(u,v,l.drift,heroX,horizon,seed,time)*.012,rm=smoothstep(surface-.008,surface+.006,rv)*(1-smoothstep(horizon,horizon+.01,rv)),a=rm*g.drift*(1-clamp01((v-horizon)*1.5))*(.35+detail*.30);r=lerp(r,8+warmBias*11,a);gg=lerp(gg,17,a);b=lerp(b,27+g.drift*11,a);}
      if(g.artifact>.01){const mode=l.artifact?.mediaMode??'cassette',wear=valueOf(l.artifact,'wear',.162)*g.artifact,wow=valueOf(l.artifact,'wow',.16)*g.artifact,nv=valueOf(l.artifact,'noise',.1)*g.artifact,tone=valueOf(l.artifact,'tone',.62),dust=(hash(px+Math.floor(time*1.5),py+seed)-.5)*nv*7;if(mode==='cassette'){r+=wear*(4+tone*6)+dust;gg+=wear*1.5+dust*.65;b-=wear*2.4-dust*.45;}else if(mode==='reel'){const f=Math.sin(v*17+time*.7)*wow*3;r+=f+dust*.5;gg+=f*.72+dust*.45;b+=f*.48+dust*.35;}else if(mode==='vinyl'){r+=dust*.72;gg+=dust*.66;b+=dust*.58;}else if(mode==='vhs'){const seam=Math.sin(py*.54+time*4.2+x*.5)*wear;r+=seam*5+dust*.42;gg+=seam*.7;b-=seam*3.4;}else if(mode==='radio'){const c=Math.sin(v*93+time*7.1)*nv*4.5;r+=c;gg+=c;b+=c*.82;}else if(mode==='wax'){const a=wear*.12,mono=(r+gg+b)/3;r=lerp(r,mono+5,a);gg=lerp(gg,mono+2,a);b=lerp(b,mono,a);}else if(mode==='broken'){const t=Math.sin(py*.78+time*8.4+seed)*wear;r+=t*8+dust;gg-=t*2;b-=t*5;}else{const a=wear*.11;r=lerp(r,33,a)+dust*.5;gg=lerp(gg,30,a)+dust*.45;b=lerp(b,24,a)+dust*.35;}}
      const hl=Math.exp(-Math.abs(v-horizon)*40);r+=hl*(5+warmBias*14);gg+=hl*10;b+=hl*12;const i=(py*RASTER_W+px)*4;data[i]=Math.max(0,Math.min(255,r));data[i+1]=Math.max(0,Math.min(255,gg));data[i+2]=Math.max(0,Math.min(255,b));data[i+3]=255;
    }} this.rasterCtx.putImageData(this.imageData,0,0);
  }

  private drawEmber(ctx:CanvasRenderingContext2D,time:number,m:ModuleState|undefined,g:Geometry,crest:number){const w=this.width,h=this.height,min=Math.min(w,h),cx=g.heroX*w,cy=g.heroY*h,amount=g.ember,mode=m?.emberMode??'velvet',drive=valueOf(m,'drive',.14),heat=valueOf(m,'heat',.18),character=valueOf(m,'character',.22),core=min*(.025+amount*.023+crest*.006);ctx.save();ctx.globalCompositeOperation='screen';if(amount>0){const glow=ctx.createRadialGradient(cx,cy,core*.55,cx,cy,core*(4.1+heat*1.4));glow.addColorStop(0,`rgba(255,215,151,${.08+amount*.10})`);glow.addColorStop(.28,`rgba(249,148,79,${.07+amount*.075})`);glow.addColorStop(.58,`rgba(221,78,176,${.035+character*.04})`);glow.addColorStop(.83,`rgba(78,213,217,${.018+amount*.022})`);glow.addColorStop(1,'rgba(78,213,217,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(cx,cy,core*(4.1+heat*1.4),0,Math.PI*2);ctx.fill();const count=mode==='console'?6:mode==='furnace'?5:mode==='exciter'||mode==='broken'?4:3;for(let i=0;i<count;i++){const p=i/Math.max(1,count-1),radius=core*(1.2+p*(2.5+drive*1.1)),wobble=mode==='furnace'?Math.sin(time*.12+i*1.8)*core*.12*heat:0,alpha=(.055+amount*.08)*(1-p*.42);ctx.strokeStyle=i%2?`rgba(222,84,181,${alpha*.72})`:`rgba(250,169,95,${alpha})`;ctx.lineWidth=Math.max(1,min*(.0014+(1-p)*.0006));ctx.beginPath();if(mode==='transformer')ctx.ellipse(cx,cy,radius*1.24,radius*.72,(i%2?-1:1)*.18,Math.PI*.06,Math.PI*1.94);else if(mode==='broken'){const start=time*.025+i*1.3;ctx.arc(cx,cy,radius+wobble,start,start+Math.PI*(.72+p*.32));}else ctx.arc(cx,cy,radius+wobble,0,Math.PI*2);ctx.stroke();}if(mode==='exciter'){ctx.strokeStyle=`rgba(244,226,186,${.035+amount*.045})`;ctx.lineWidth=1;for(let i=0;i<10;i++){const a=i/10*Math.PI*2+time*.006,inner=core*1.25,outer=core*(2.1+character*1.7+(i%3)*.18);ctx.beginPath();ctx.moveTo(cx+Math.cos(a)*inner,cy+Math.sin(a)*inner);ctx.lineTo(cx+Math.cos(a)*outer,cy+Math.sin(a)*outer);ctx.stroke();}}}ctx.restore();ctx.save();ctx.fillStyle='rgba(1,3,7,.985)';ctx.beginPath();ctx.arc(cx,cy,core*.82,0,Math.PI*2);ctx.fill();ctx.strokeStyle=amount>0?`rgba(246,205,146,${.10+amount*.09})`:'rgba(116,151,150,.07)';ctx.lineWidth=Math.max(1,min*.0015);ctx.stroke();ctx.restore();}

  private drawHalo(ctx:CanvasRenderingContext2D,time:number,m:ModuleState|undefined,g:Geometry,s:SceneState){if(!m||g.halo<=0||m.delayAlgorithm!=='constellation')return;const w=this.width,h=this.height,seed=lerp(s.a.seed,s.b.seed,s.mix),sym=lerp(s.a.symmetry,s.b.symmetry,s.mix);ctx.save();ctx.globalCompositeOperation='screen';for(let i=0;i<9;i++){const u=.08+i/8*.84,x=u*w,y=this.mountainSurface(u,g.horizon,m,seed,time,sym)*h-3-(i%3)*2;ctx.fillStyle=i%2?`rgba(82,216,220,${.10+g.halo*.10})`:`rgba(244,181,108,${.10+g.halo*.10})`;ctx.beginPath();ctx.arc(x,y,.7+(i%3)*.35,0,Math.PI*2);ctx.fill();}ctx.restore();}
  private drawAtmos(ctx:CanvasRenderingContext2D,time:number,m:ModuleState|undefined,g:Geometry){if(!m||g.atmos<=0)return;const mode=m.algorithm??'hall';if(mode!=='aurora'&&mode!=='celestial')return;const w=this.width,h=this.height,hz=g.horizon*h;ctx.save();ctx.globalCompositeOperation='screen';if(mode==='aurora'){for(let i=0;i<4;i++){const grad=ctx.createLinearGradient(w*.12,0,w*.88,0);grad.addColorStop(0,'rgba(77,214,218,0)');grad.addColorStop(.38,`rgba(77,214,218,${.025+g.atmos*.028})`);grad.addColorStop(.62,`rgba(218,83,184,${.020+g.atmos*.024})`);grad.addColorStop(1,'rgba(218,83,184,0)');ctx.strokeStyle=grad;ctx.lineWidth=1;ctx.beginPath();for(let step=0;step<=30;step++){const p=step/30,x=w*(.08+p*.84),y=hz*(.18+i*.10)+Math.sin(p*Math.PI*2+time*.08+i)*h*.025;step===0?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.stroke();}}else{const cx=g.heroX*w,cy=g.heroY*h,r=Math.min(w,h)*(.18+g.atmos*.08),glow=ctx.createRadialGradient(cx,cy,0,cx,cy,r);glow.addColorStop(0,`rgba(228,239,233,${.025+g.atmos*.035})`);glow.addColorStop(.45,`rgba(88,151,255,${.012+g.atmos*.018})`);glow.addColorStop(1,'rgba(88,151,255,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();}ctx.restore();}
  private drawDrift(ctx:CanvasRenderingContext2D,time:number,m:ModuleState|undefined,g:Geometry){if(!m||g.drift<=0)return;const w=this.width,h=this.height,hz=g.horizon*h,cx=g.heroX*w,mode=m.driftMode??'chorus',spread=valueOf(m,'spread',.62),motion=valueOf(m,'motion',.32);ctx.save();ctx.globalCompositeOperation='screen';const count=mode==='ensemble'?7:mode==='liquid'?5:4;for(let i=0;i<count;i++){const p=(i+1)/(count+1),y=lerp(hz+h*.06,h*.91,p),half=w*(.08+p*(.24+spread*.16)),wobble=Math.sin(time*(.035+motion*.05)+i*1.2)*h*.004;ctx.strokeStyle=i%2?`rgba(77,214,218,${.022+g.drift*.025})`:`rgba(218,83,184,${.016+g.drift*.020})`;ctx.lineWidth=1;ctx.beginPath();if(mode==='rotary'||mode==='orbit')ctx.ellipse(cx,y,half,h*(.012+p*.025),(this.x-.5)*.05,Math.PI,Math.PI*2);else{ctx.moveTo(cx-half,y+wobble);ctx.quadraticCurveTo(cx,y-h*(.006+g.drift*.006),cx+half,y-wobble);}ctx.stroke();}ctx.restore();}
  private drawGrain(ctx:CanvasRenderingContext2D,time:number,m:ModuleState|undefined,g:Geometry){if(!m||g.grain<=0)return;const w=this.width,h=this.height,mode=m.grainMode??'reconstruct',density=valueOf(m,'density',.42),chaos=valueOf(m,'chaos',.16),bloom=valueOf(m,'bloom',.36),pitch=valueOf(m,'pitch',.38),count=10+Math.round(density*34+g.grain*8),speed=.035+density*.045+pitch*.025;ctx.save();ctx.globalCompositeOperation='screen';for(let i=0;i<count;i++){const seed=hash(i*11.31+4.7),lateral=hash(i*17.2+2.3);let fall=(time*speed*(.72+seed*.56)+seed)%1;if(mode==='stutter')fall=Math.floor(fall*12)/12;const x=lateral*w+Math.sin(time*.04+i)*chaos*w*.012,y=-h*.08+fall*h*1.12,alpha=(.025+g.grain*.035)*(.55+seed*.45);if(mode==='shatter'||mode==='ruin'){const size=1.1+seed*(2.2+chaos*2.2);ctx.fillStyle=mode==='ruin'?`rgba(229,132,189,${alpha*.76})`:`rgba(116,223,221,${alpha})`;ctx.beginPath();ctx.moveTo(x,y-size);ctx.lineTo(x+size*.8,y+size*.4);ctx.lineTo(x-size*.6,y+size);ctx.closePath();ctx.fill();}else{const len=mode==='smear'?11+bloom*15:mode==='prism'?5+bloom*7:4+density*7;ctx.strokeStyle=mode==='prism'?(i%3===0?`rgba(244,173,99,${alpha})`:i%2?`rgba(220,88,187,${alpha})`:`rgba(86,216,220,${alpha})`):`rgba(196,229,222,${alpha})`;ctx.lineWidth=mode==='smear'?1.1:.8;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+chaos*2.8,y+len);ctx.stroke();}}ctx.restore();}
  private drawArtifact(ctx:CanvasRenderingContext2D,time:number,m:ModuleState|undefined,g:Geometry){if(!m||g.artifact<=0)return;const w=this.width,h=this.height,mode=m.mediaMode??'cassette',wear=valueOf(m,'wear',.162)*g.artifact,wow=valueOf(m,'wow',.16)*g.artifact,nv=valueOf(m,'noise',.1)*g.artifact;ctx.save();ctx.globalCompositeOperation='screen';if(mode==='vhs'||mode==='broken'){const lines=mode==='broken'?4:2;for(let i=0;i<lines;i++){const y=(hash(Math.floor(time*(.45+i*.12))+i*9.2)*.78+.1)*h,shift=Math.sin(time*1.3+i)*(1+wear*(mode==='broken'?8:3));ctx.strokeStyle=i%2?`rgba(83,216,220,${.018+wear*.045})`:`rgba(225,92,188,${.016+wear*.040})`;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y+shift);ctx.stroke();}}else if(mode==='vinyl'){for(let i=0;i<5;i++){const x=hash(i*7.7+Math.floor(time*.15))*w,y=hash(i*5.1+3.2)*h;ctx.fillStyle=`rgba(236,220,181,${.018+nv*.055})`;ctx.beginPath();ctx.arc(x,y,.6+(i%2)*.4,0,Math.PI*2);ctx.fill();}}else if(mode==='radio'){const y=((time*.12)%1)*h,grad=ctx.createLinearGradient(0,y-12,0,y+12);grad.addColorStop(0,'rgba(85,216,220,0)');grad.addColorStop(.5,`rgba(218,232,220,${.012+nv*.035})`);grad.addColorStop(1,'rgba(85,216,220,0)');ctx.fillStyle=grad;ctx.fillRect(0,y-12,w,24);}else if(mode==='reel'||mode==='cassette'){const x=w*(.5+Math.sin(time*.045)*wow*.03),sheen=ctx.createLinearGradient(x-w*.22,0,x+w*.22,0);sheen.addColorStop(0,'rgba(245,171,100,0)');sheen.addColorStop(.5,`rgba(245,171,100,${.010+wear*.024})`);sheen.addColorStop(1,'rgba(245,171,100,0)');ctx.fillStyle=sheen;ctx.fillRect(0,0,w,h);}else if(mode==='archive'){ctx.fillStyle=`rgba(235,205,153,${.008+wear*.020})`;ctx.fillRect(0,0,w,h);}ctx.restore();}
}
