# CMake generated Testfile for 
# Source directory: /home/runner/work/calcotone/calcotone/native
# Build directory: /home/runner/work/calcotone/calcotone/native/build-portable
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[core_contract_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/core_contract_test")
set_tests_properties([=[core_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;181;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[stack_amp_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/stack_amp_test")
set_tests_properties([=[stack_amp_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;182;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[native_rack_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/native_rack_test")
set_tests_properties([=[native_rack_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;183;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[pitch_tracker_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/pitch_tracker_test")
set_tests_properties([=[pitch_tracker_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;184;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[native_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/native_processor_test")
set_tests_properties([=[native_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;185;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[audio_device_config_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/audio_device_config_test")
set_tests_properties([=[audio_device_config_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;186;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[audio_client_property_plan_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/audio_client_property_plan_test")
set_tests_properties([=[audio_client_property_plan_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;187;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[audio_restart_policy_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/audio_restart_policy_test")
set_tests_properties([=[audio_restart_policy_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;188;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[elastic_stereo_fifo_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/elastic_stereo_fifo_test")
set_tests_properties([=[elastic_stereo_fifo_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;189;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[elastic_stereo_fifo_discontinuity_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/elastic_stereo_fifo_discontinuity_test")
set_tests_properties([=[elastic_stereo_fifo_discontinuity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;190;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[stream_recovery_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/stream_recovery_test")
set_tests_properties([=[stream_recovery_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;191;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[adaptive_fifo_safety_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/adaptive_fifo_safety_test")
set_tests_properties([=[adaptive_fifo_safety_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;192;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[atmos_parity_profile_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/atmos_parity_profile_test")
set_tests_properties([=[atmos_parity_profile_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;193;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[atmos_parity_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/atmos_parity_processor_test")
set_tests_properties([=[atmos_parity_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;194;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[atmos_lexicon224_converter_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/atmos_lexicon224_converter_test")
set_tests_properties([=[atmos_lexicon224_converter_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;195;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[native_atmos_live_parity_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/native_atmos_live_parity_test")
set_tests_properties([=[native_atmos_live_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;196;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[ember_parity_profile_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/ember_parity_profile_test")
set_tests_properties([=[ember_parity_profile_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;197;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[ember_parity_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/ember_parity_processor_test")
set_tests_properties([=[ember_parity_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;198;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[ember_magnetic_core_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/ember_magnetic_core_processor_test")
set_tests_properties([=[ember_magnetic_core_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;199;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[ember_digital_capture_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/ember_digital_capture_processor_test")
set_tests_properties([=[ember_digital_capture_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;200;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[native_ember_live_parity_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/native_ember_live_parity_test")
set_tests_properties([=[native_ember_live_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;201;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[drift_parity_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/drift_parity_processor_test")
set_tests_properties([=[drift_parity_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;202;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[drift_classic_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/drift_classic_processor_test")
set_tests_properties([=[drift_classic_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;203;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[drift_standard_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/drift_standard_processor_test")
set_tests_properties([=[drift_standard_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;204;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[halo_parity_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/halo_parity_processor_test")
set_tests_properties([=[halo_parity_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;205;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[halo_space_echo_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/halo_space_echo_processor_test")
set_tests_properties([=[halo_space_echo_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;206;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[grain_parity_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/grain_parity_processor_test")
set_tests_properties([=[grain_parity_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;207;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[native_grain_live_parity_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/native_grain_live_parity_test")
set_tests_properties([=[native_grain_live_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;208;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[artifact_parity_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/artifact_parity_processor_test")
set_tests_properties([=[artifact_parity_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;209;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[native_artifact_live_parity_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/native_artifact_live_parity_test")
set_tests_properties([=[native_artifact_live_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;210;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[stomp_parity_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/stomp_parity_processor_test")
set_tests_properties([=[stomp_parity_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;211;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[native_stomp_live_parity_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/native_stomp_live_parity_test")
set_tests_properties([=[native_stomp_live_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;212;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[pressure_parity_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/pressure_parity_processor_test")
set_tests_properties([=[pressure_parity_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;213;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[native_pressure_live_parity_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/native_pressure_live_parity_test")
set_tests_properties([=[native_pressure_live_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;214;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[dream_buffer_parity_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/dream_buffer_parity_processor_test")
set_tests_properties([=[dream_buffer_parity_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;215;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[native_dream_engine_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/native_dream_engine_test")
set_tests_properties([=[native_dream_engine_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;216;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[native_dream_live_parity_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/native_dream_live_parity_test")
set_tests_properties([=[native_dream_live_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;217;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
add_test([=[halo_dual_grain_pitch_processor_test]=] "/home/runner/work/calcotone/calcotone/native/build-portable/halo_dual_grain_pitch_processor_test")
set_tests_properties([=[halo_dual_grain_pitch_processor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;218;add_test;/home/runner/work/calcotone/calcotone/native/CMakeLists.txt;0;")
